# Bu dosya, ana script tarafından kullanılacak olan çok dilli metinleri içerir.
# Yeni bir dil eklemek için, switch bloğuna yeni bir bölüm (örneğin, 'de' Almanca için) ekleyin
# ve $langStrings hash tablosunu o dil için doldurun.

# Ana script tarafından belirlenen global dili kullanarak uygun metin setini seçer.
switch ($global:currentLanguage) {
    'tr' {
        $global:langStrings = @{
            # Genel
            pressAnyKey                = "Devam etmek icin herhangi bir tusa basin..."
            promptChoice               = "Seciminiz"
            goBack                     = "Geri"
            invalidChoice              = "Gecersiz secim!"
            # Banner
            bannerTitle                = "Windows 11 ISO Özelleştirme Aracı"
            # Hata Yönetimi (Trap)
            trapErrorUnexpected        = "Beklenmedik bir hata olustu! Guvenli cikis yapiliyor..."
            trapErrorMessage           = "Hata:"
            trapErrorFallback          = "Beklenmedik bir hata olustu! Guvenli cikis yapiliyor..." # Dil dosyası yüklenemezse kullanılır
            trapMessageFallback        = "Hata:" # Dil dosyası yüklenemezse kullanılır
            # Uzun Süren İşlemler
            longOpFailed               = "Arka plan isleminde hata olustu: {0}"
            longOpSavingImage          = "Image degisiklikleri kaydediliyor, bu islem uzun surebilir..."
            # Get-UserChoice
            getUserChoiceMultiSelect   = "Birden fazla secim yapabilirsiniz (orn: 1,3,5), 'tumu' veya 'g' (geri):"
            getUserChoiceSingleSelect  = "Seciminiz (1-{0} veya 'g')"
            # Get-IsoTool
            isoToolOscdimgFound        = "Sistemde kurulu oscdimg.exe bulundu."
            isoToolMkisofsNotFound     = "Sistemde oscdimg.exe bulunamadi. Alternatif arac (mkisofs) indiriliyor..."
            isoToolMkisofsExists       = "mkisofs zaten indirilmis."
            isoToolDownloadingMkisofs  = "mkisofs.exe indiriliyor..."
            isoToolDownloadingCygwin   = "cygwin1.dll indiriliyor..."
            isoToolDownloadSuccess     = "mkisofs basariyla indirildi."
            isoToolDownloadError       = "Hata: Alternatif ISO araci indirilemedi. {0}"
            isoToolDownloadHelp        = "Lutfen internet baglantinizi kontrol edin veya Windows ADK'yi yukleyin."
            isoToolDownloadFail        = "Indirme basarisiz oldu."
            # Import/Export
            importTitle                = "Kaydedilmis bir yapilandirma dosyasini ice aktarmak ister misiniz?"
            importDesc                 = "Evet derseniz, islemler yapilandirma dosyaniza gore otomatik olarak yapilacaktir."
            importPrompt               = "Seciminiz (E/H)"
            importFileSelectTitle      = "Yapilandirma dosyasini secin (.json)"
            importReadingFile          = "Yapilandirma dosyasi okunuyor: {0}"
            importSuccess              = "Yapilandirma basariyla yuklendi! Otomatik mod baslatiliyor..."
            importReadError            = "Yapilandirma dosyasi okunurken hata olustu: {0}"
            importFileNotSelected      = "Dosya secilmedi. Manuel yapilandirmaya devam ediliyor."
            importManualContinue       = "Manuel yapilandirmaya devam ediliyor."
            exportTitle                = "Mevcut ayarlar bir .json dosyasina aktarilacak."
            exportFileSaveTitle        = "Yapilandirma dosyasini kaydet"
            exportSuccess              = "Yapilandirma basariyla kaydedildi: {0}"
            exportError                = "Dosya kaydedilirken hata olustu: {0}"
            exportCanceled             = "Disa aktarma islemi iptal edildi."
            exportFileName             = "Yapılandırma Dosyam.json"
            exportConfigDesc           = "Windows 11 Özelleştirme Ayarları"
            # Ortam Hazırlama
            initEnvPreparing           = "Calisma ortami hazirlaniyor..."
            initEnvSuccess             = "Ortam hazirlandi!"
            initEnvError               = "Ortam hazırlanırken hata oluştu: {0}"
            initEnvFail                = "Ortam hazırlanamadı."
            # ISO Kopyalama
            copyIsoCopying             = "ISO dosyalari kopyalaniyor..."
            copyIsoUnlockingWim        = "install.wim dosyasinin salt okunur ozelligi kaldiriliyor..."
            copyIsoSuccess             = "ISO dosyalari kopyalandi!"
            copyIsoError               = "ISO dosyaları kopyalanırken hata oluştu: {0}"
            copyIsoFail                = "ISO kopyalama başarısız."
            # DISM Bulma
            dismFound                  = "DISM bulundu: {0}"
            dismFoundInPath            = "DISM PATH'te bulundu: {0}"
            dismNotFoundWarning        = "UYARI: DISM bulunamadi! Windows ADK veya system DISM gerekli."
            dismNotFoundExit           = "DISM bulunamadığı için script sonlandırılıyor."
            # Sürüm Kaldırma
            removeEditionsAnalyzing    = "Mevcut Windows surumleri analiz ediliyor..."
            removeEditionsCurrent      = "Mevcut surumler:"
            removeEditionsOnlyOne      = "Yalnizca bir surum kaldi. Silme islemi atlandi."
            removeEditionsPrompt       = "Kaldirmak istediginiz surumlerin index numaralarini girin (virgulle ayirarak, orn: 1,3)"
            removeEditionsGoBack       = "[g] Geri don ve duzenlenecek surumu sec"
            removeEditionsInvalidIndex = "Gecersiz index numarasi bulundu: {0}. Lutfen 1 ile {1} arasinda degerler girin."
            removeEditionsRemoving     = "Index {0} kaldiriliyor..."
            removeEditionsSuccess      = "Index {0} basariyla kaldirildi!"
            removeEditionsError        = "Index {0} kaldirilirken hata olustu: {1}"
            removeEditionsListUpdated  = "Secilen surumler kaldirildi. Liste guncelleniyor..."
            removeEditionsInvalidInput = "Gecersiz giris! Lutfen sayilari virgulle ayirarak girin (orn: 1,3)."
            # Image Mount Etme
            mountListingEditions       = "Mevcut Windows surumleri listeleniyor..."
            mountMountingImage         = "Windows imaji C:\mount dizinine mount ediliyor..."
            mountSuccess               = "Image basariyla mount edildi!"
            mountError                 = "Image mount edilirken hata olustu: {0}"
            mountFail                  = "Mount işlemi başarısız."
            mountPromptIndex           = "Duzenleme yapmak istediginiz Windows surumunun index numarasini girin"
            mountInvalidIndex          = "Gecersiz index numarasi."
            # Güncelleme Ekleme
            updatesPromptPath          = "Guncellemelerin bulundugu klasorun yolunu girin"
            updatesAdding              = "Guncellemeler ekleniyor..."
            updatesAddingFile          = "Ekleniyor: {0}"
            updatesAddedFile           = "Eklendi: {0}"
            updatesErrorFile           = "{0} eklenirken hata olustu: {1}"
            updatesMsuNotFound         = "Belirtilen yolda .msu uzantili guncelleme dosyasi bulunamadi."
            updatesInvalidPath         = "Gecersiz klasor yolu!"
            # Sürücü Ekleme
            driversPromptPath          = "Suruculerin bulundugu ana klasorun yolunu girin"
            driversAdding              = "Suruculer ekleniyor..."
            driversSuccess             = "Suruculer basariyla eklendi."
            driversError               = "Suruculer eklenirken hata olustu: {0}"
            # Bileşen ve Servisler
            compSvcTitle               = "Bilesenleri Kaldir ve Servisleri Yapilandir"
            compSvcApplyingFromConfig  = "Yapilandirma dosyasindan bilesen ve servis ayarlari uygulaniyor..."
            compSvcApplyAll            = "TUMUNU UYGULA"
            compSvcNothingSelected     = "Uygulanacak ayar secilmedi."
            compSvcConfiguringServices = "Servisler yapilandiriliyor..."
            compSvcServiceDisabled     = " -> '{0}' servisi devre disi birakildi."
            compSvcServiceNotFound     = " -> '{0}' servisi bulunamadi, atlandi."
            compSvcServiceError        = " -> '{0}' servisi yapilandirilirken hata: {1}"
            compSvcRemovingComponents  = "Bilesenler kaldiriliyor..."
            compSvcProcessing          = "Islem yapiliyor: {0}"
            compSvcStateEnabled        = " -> Durum: Etkin. Kaldiriliyor..."
            compSvcRemoveSuccess       = " -> Basariyla kaldirildi."
            compSvcRemoveError         = " -> Kaldirilirken hata olustu. DISM Exit Code: {0}"
            compSvcStateNotEnabled     = " -> Bilesen etkin degil (Durum: {0}). Islem atlandi."
            compSvcStateError          = " -> Bilesen durumu okunamadi veya bilesen bulunamadi. Islem atlandi."
            compSvcCriticalError       = " -> Bilesen durumu kontrol edilirken veya kaldirilirken kritik hata: {0}"
            compSvcTweakDefNotFound    = "KRITIK HATA: component-definitions.ps1 bulunamadi veya yuklenemedi."
            # Registry Ayarları
            regMenuTitle               = "Registry Yapılandırma Menüsü"
            regApplyingFromConfig      = "Yapilandirma dosyasindan registry ayarlari uygulaniyor..."
            regCurrentSelections       = "Su anki secimleriniz:"
            regSelectAll               = "TUM AYARLARI SEÇ/KALDIR"
            regGoBackAndApply          = "[g] Geri (Ana Menüye Dön ve Seçimleri Uygula)"
            regPrompt                  = "Seciminiz (Birden fazla secim icin virgulle ayirin, orn: 1,5,12)"
            regAllSelectionsRemoved    = "Tum secimler kaldirildi."
            regAllSelectionsAdded      = "Tum ayarlar secildi."
            regItemRemoved             = "'{0}' secimlerden kaldirildi."
            regItemAdded               = "'{0}' secimlere eklendi."
            regInvalidNumber           = "Gecersiz numara: {0}"
            regInvalidInput            = "Giris sadece sayi ve virgul icermelidir. Hatali bolum: '{0}'"
            regWarnMultiUpdate         = "Uyari: Birden fazla Windows Update ayari secildi. Yalnizca ilki uygulanacak: '{0}'"
            regNothingSelected         = "Uygulanacak registry ayari secilmedi."
            regApplying                = "Uygulaniyor: {0}"
            regSuccess                 = " -> Basarili."
            regFail                    = " -> Yapilandirma BASARISIZ oldu: {0}. Hata: {1}"
            regQueuedForPostSetup      = " -> Kurulum sonrasi icin siraya eklendi."
            regPostSetupScriptCreated  = "Kurulum sonrasi PowerShell script'i basariyla olusturuldu."
            regManualRunnerCreated     = "Masaustu icin manuel calistirici ({0}) olusturuldu."
            regErrorGeneral            = "Registry işlemleri sırasında bir hata oluştu: {0}"
            regSaving                  = "Registry yapilandirmasi kaydediliyor..."
            regComplete                = "Registry yapilandirmasi tamamlandi."
            regReturnToMenu            = "Ana menüye dönmek için herhangi bir tuşa basın..."
            regTweakDefNotFound        = "KRITIK HATA: tweak-definitions.ps1 bulunamadi veya yuklenemedi."
            regRunnerBatTitle          = "Ozel Ayarlari Uygula.bat"
            regRunnerBatBody           = "@echo off`necho.`necho Bu script, ISO'ya eklenen ozel ayarlari uygulayacaktir.`necho Lutfen internet baglantinizin aktif oldugundan emin olun.`necho.`npause`necho Ayarlar uygulaniyor, lutfen bekleyin...`npowershell.exe -ExecutionPolicy Bypass -File ""{0}""`necho.`necho Islem tamamlandi. Bu pencere simdi kapatilacak ve bu baslatici silinecek.`ntimeout /t 5`ndel ""%~f0"""
            # Uygulama Kaldırma
            appRemoveGettingList       = "ISO icindeki kurulu uygulamalarin listesi aliniyor. Bu islem biraz surebilir..."
            appRemoveGetListError      = "Uygulama listesi alinamadi. DISM Exit Code: {0}"
            appRemoveExcludingCritical = "Kritik sistem uygulamalari liste disi birakiliyor..."
            appRemoveNotFound          = "Kaldirilabilecek uygulama bulunamadi."
            appRemoveTitle             = "Hangi uygulamalari kaldirmak istiyorsunuz?"
            appRemoveApplyAll          = "TUMUNU UYGULA"
            appRemoveFromConfig        = "Yapilandirma dosyasindan uygulamalar kaldiriliyor..."
            appRemoveNothingSelected   = "Kaldirilacak uygulama secilmedi."
            appRemoveStarting          = "Kaldirma islemi basliyor..."
            appRemoveRemoving          = "Kaldiriliyor: {0}"
            appRemoveSuccess           = "Basarili bir sekilde kaldirildi: {0}"
            appRemoveFail              = "Kaldirilamadi: {0}. DISM Exit Code: {1}"
            appRemoveError             = "{0} kaldirilirken hata: {1}"
            appRemoveComplete          = "Uygulama kaldirma islemi tamamlandi."
            appExclusionDefNotFound    = "KRITIK HATA: app-exclusion-list.ps1 bulunamadi veya yuklenemedi."
            # Özellik Ekleme
            featureEnableFromConfig    = "Yapilandirma dosyasindan ozellikler etkinlestiriliyor..."
            featureEnableTitle         = "Hangi ozellikleri etkinlestirmek istiyorsunuz?"
            featureEnableApplyAll      = "Tum onerilen ozellikleri etkinlestir"
            featureEnableNothingSelect = "Etkinlestirilecek ozellik secilmedi."
            featureEnableEnabling      = "{0} etkinlestiriliyor..."
            featureEnableSuccess       = "{0} basariyla etkinlestirildi."
            featureEnableError         = "Hata: {0} etkinlestirilemedi. {1}"
            featureDefNotFound         = "KRITIK HATA: feature-definitions.ps1 bulunamadi veya yuklenemedi."
            # Tamamlama
            completeCreatingIso        = "Yeni ISO olusturuluyor..."
            completeToolNotFound       = "ISO olusturma araci bulunamadi veya indirilemedi. Islem iptal ediliyor."
            completeToolNotFoundHelp   = "Degisiklikleriniz C:\temp_iso klasorunde hazir durumda. ISO'yu manuel olusturabilirsiniz."
            completeSaveFileTitle      = "Cikti ISO dosyasinin kaydedilecegi yeri secin"
            completeOutputCanceled     = "Cikti yolu secilmedi. ISO olusturma iptal edildi."
            completeOutputIsoPath      = "Cikti ISO dosyasi yolu: {0}"
            completeIsoSuccess         = "ISO basariyla olusturuldu: {0}"
            completeIsoError           = "ISO olusturulurken hata olustu: {0}"
            completeFilesSaved         = "Dosyalariniz C:\temp_iso klasorunde korunuyor."
            completeUnmountFail        = "Unmount/Commit islemi basarisiz oldu. Cikis Kodu: {0}"
            completeSaveError          = "`nImage kaydedilirken kritik bir hata olustu: {0}"
            completeFinalizeFail       = "Image sonlandirilamadi."
            completeDefaultIsoName     = "Ozel_Windows11.iso"
            # Temizlik
            cleanupCleaning            = "Gecici dosyalar ve klasorler temizleniyor..."
            cleanupImageMounted        = "Hala mount edilmis bir imaj var, degisiklikler iptal ediliyor..."
            cleanupComplete            = "Temizlik tamamlandi!"
            # Script Başlangıcı
            langPrompt                 = "Lutfen bir dil secin / Please select a language"
            scriptNotAdmin             = "Bu script yonetici olarak calistirilmalidir!"
            scriptExistingMount        = "Mevcut bir mount islemi bulundu. Dogrudan menuye geciliyor..."
            scriptSelectIso            = "Windows 11 ISO dosyasini secin"
            scriptIsoNotSelected       = "ISO dosyasi secilmedi. Script sonlandiriliyor."
            scriptIsoSelected          = "Secilen ISO dosyasi: {0}"
            scriptIsoInvalid           = "ISO dosyasi bulunamadi veya gecersiz: {0}"
            scriptIsoFound             = "ISO dosyasi bulundu: {0}"
            scriptMountFail            = "Image mount edilemedi. Script sonlandiriliyor."
            scriptPromptUpdate         = "Windows Guncellemesi eklemek ister misiniz? (E/H)"
            scriptPromptDriver         = "Surucu eklemek ister misiniz? (E/H)"
            # Yürütme Bloğu
            execAutoModeStarted        = "--- OTOMATIK ISLEMLER BASLATILDI ---"
            execAutoModeCompleted      = "--- OTOMATIK ISLEMLER TAMAMLANDI ---"
            execAutoPromptManual       = "Otomatik islemler tamamlandi. Ekstra bir islem yapmak (manuel moda gecmek) ister misiniz? (E/H)"
            execAutoCreateIso          = "ISO olusturma asamasina geciliyor..."
            # Ana Menü
            mainMenu1                  = "1. Windows Guncellemesi Ekle (.msu)"
            mainMenu2                  = "2. Surucu Ekle (.inf)"
            mainMenu3                  = "3. Bilesenleri Kaldir ve Servisleri Yapilandir"
            mainMenu4                  = "4. Registry Ayarlarini Yapilandir"
            mainMenu5                  = "5. Windows Uygulamalarini Kaldir"
            mainMenu6                  = "6. Windows Ozelliklerini Etkinlestir"
            mainMenu7                  = "7. Ayarlari Disa Aktar (.json)"
            mainMenu8                  = "8. Degisiklikleri Kaydet ve ISO Olustur"
            mainMenu9                  = "9. Degisiklikleri Kaydetme ve Cik"
            # Bitiş
            finishMessage              = "Islem tamamlandi. Cikmak icin herhangi bir tusa basin..."
        }
    }
    'en' {
        $global:langStrings = @{
            # General
            pressAnyKey                = "Press any key to continue..."
            promptChoice               = "Your choice"
            goBack                     = "Back"
            invalidChoice              = "Invalid choice!"
            # Banner
            bannerTitle                = "Windows 11 ISO Customization Tool"
            # Trap
            trapErrorUnexpected        = "An unexpected error occurred! Exiting safely..."
            trapErrorMessage           = "Error:"
            trapErrorFallback          = "An unexpected error occurred! Exiting safely..." # Fallback if lang file fails
            trapMessageFallback        = "Error:" # Fallback if lang file fails
            # Long Running Operation
            longOpFailed               = "An error occurred in the background job: {0}"
            longOpSavingImage          = "Saving image changes, this may take a long time..."
            # Get-UserChoice
            getUserChoiceMultiSelect   = "You can make multiple selections (e.g., 1,3,5), 'all' or 'g' (back):"
            getUserChoiceSingleSelect  = "Your choice (1-{0} or 'g')"
            # Get-IsoTool
            isoToolOscdimgFound        = "Found installed oscdimg.exe."
            isoToolMkisofsNotFound     = "oscdimg.exe not found. Downloading alternative tool (mkisofs)..."
            isoToolMkisofsExists       = "mkisofs is already downloaded."
            isoToolDownloadingMkisofs  = "Downloading mkisofs.exe..."
            isoToolDownloadingCygwin   = "Downloading cygwin1.dll..."
            isoToolDownloadSuccess     = "mkisofs downloaded successfully."
            isoToolDownloadError       = "Error: Could not download the alternative ISO tool. {0}"
            isoToolDownloadHelp        = "Please check your internet connection or install the Windows ADK."
            isoToolDownloadFail        = "Download failed."
            # Import/Export
            importTitle                = "Would you like to import a saved configuration file?"
            importDesc                 = "If yes, operations will be performed automatically based on your configuration file."
            importPrompt               = "Your choice (Y/N)"
            importFileSelectTitle      = "Select the configuration file (.json)"
            importReadingFile          = "Reading configuration file: {0}"
            importSuccess              = "Configuration loaded successfully! Starting automatic mode..."
            importReadError            = "Error reading configuration file: {0}"
            importFileNotSelected      = "No file selected. Continuing with manual configuration."
            importManualContinue       = "Continuing with manual configuration."
            exportTitle                = "Current settings will be exported to a .json file."
            exportFileSaveTitle        = "Save configuration file"
            exportSuccess              = "Configuration successfully saved: {0}"
            exportError                = "Error saving file: {0}"
            exportCanceled             = "Export operation canceled."
            exportFileName             = "My Configuration File.json"
            exportConfigDesc           = "Windows 11 Customization Settings"
            # Environment Init
            initEnvPreparing           = "Preparing working environment..."
            initEnvSuccess             = "Environment prepared!"
            initEnvError               = "Error preparing environment: {0}"
            initEnvFail                = "Could not prepare environment."
            # ISO Copy
            copyIsoCopying             = "Copying ISO files..."
            copyIsoUnlockingWim        = "Removing read-only attribute from install.wim..."
            copyIsoSuccess             = "ISO files copied!"
            copyIsoError               = "Error copying ISO files: {0}"
            copyIsoFail                = "ISO copy failed."
            # DISM Find
            dismFound                  = "DISM found: {0}"
            dismFoundInPath            = "DISM found in PATH: {0}"
            dismNotFoundWarning        = "WARNING: DISM not found! Windows ADK or system DISM is required."
            dismNotFoundExit           = "Exiting script because DISM could not be found."
            # Remove Editions
            removeEditionsAnalyzing    = "Analyzing current Windows editions..."
            removeEditionsCurrent      = "Current editions:"
            removeEditionsOnlyOne      = "Only one edition left. Skipping deletion."
            removeEditionsPrompt       = "Enter the index numbers of the editions to remove (comma-separated, e.g., 1,3)"
            removeEditionsGoBack       = "[g] Go back and select edition to edit"
            removeEditionsInvalidIndex = "Invalid index number found: {0}. Please enter values between 1 and {1}."
            removeEditionsRemoving     = "Removing index {0}..."
            removeEditionsSuccess      = "Index {0} successfully removed!"
            removeEditionsError        = "Error removing index {0}: {1}"
            removeEditionsListUpdated  = "Selected editions removed. Updating list..."
            removeEditionsInvalidInput = "Invalid input! Please enter numbers separated by commas (e.g., 1,3)."
            # Mount Image
            mountListingEditions       = "Listing current Windows editions..."
            mountMountingImage         = "Mounting Windows image to C:\mount..."
            mountSuccess               = "Image mounted successfully!"
            mountError                 = "Error mounting image: {0}"
            mountFail                  = "Mount operation failed."
            mountPromptIndex           = "Enter the index number of the Windows edition you want to edit"
            mountInvalidIndex          = "Invalid index number."
            # Add Updates
            updatesPromptPath          = "Enter the path to the folder containing the updates"
            updatesAdding              = "Adding updates..."
            updatesAddingFile          = "Adding: {0}"
            updatesAddedFile           = "Added: {0}"
            updatesErrorFile           = "Error adding {0}: {1}"
            updatesMsuNotFound         = "No update file with .msu extension found in the specified path."
            updatesInvalidPath         = "Invalid folder path!"
            # Add Drivers
            driversPromptPath          = "Enter the path to the main folder containing the drivers"
            driversAdding              = "Adding drivers..."
            driversSuccess             = "Drivers added successfully."
            driversError               = "Error adding drivers: {0}"
            # Components and Services
            compSvcTitle               = "Remove Components and Configure Services"
            compSvcApplyingFromConfig  = "Applying component and service settings from configuration file..."
            compSvcApplyAll            = "APPLY ALL"
            compSvcNothingSelected     = "No setting selected to apply."
            compSvcConfiguringServices = "Configuring services..."
            compSvcServiceDisabled     = " -> Service '{0}' disabled."
            compSvcServiceNotFound     = " -> Service '{0}' not found, skipped."
            compSvcServiceError        = " -> Error configuring service '{0}': {1}"
            compSvcRemovingComponents  = "Removing components..."
            compSvcProcessing          = "Processing: {0}"
            compSvcStateEnabled        = " -> State: Enabled. Removing..."
            compSvcRemoveSuccess       = " -> Successfully removed."
            compSvcRemoveError         = " -> Error during removal. DISM Exit Code: {0}"
            compSvcStateNotEnabled     = " -> Component not enabled (State: {0}). Operation skipped."
            compSvcStateError          = " -> Could not read component state or component not found. Operation skipped."
            compSvcCriticalError       = " -> Critical error while checking or removing component state: {0}"
            compSvcTweakDefNotFound    = "CRITICAL ERROR: component-definitions.ps1 could not be found or loaded."
            # Registry Tweaks
            regMenuTitle               = "Registry Configuration Menu"
            regApplyingFromConfig      = "Applying registry settings from configuration file..."
            regCurrentSelections       = "Your current selections:"
            regSelectAll               = "SELECT/DESELECT ALL TWEAKS"
            regGoBackAndApply          = "[g] Back (Return to Main Menu and Apply Selections)"
            regPrompt                  = "Your choice (separate multiple choices with a comma, e.g., 1,5,12)"
            regAllSelectionsRemoved    = "All selections have been removed."
            regAllSelectionsAdded      = "All tweaks have been selected."
            regItemRemoved             = "'{0}' removed from selections."
            regItemAdded               = "'{0}' added to selections."
            regInvalidNumber           = "Invalid number: {0}"
            regInvalidInput            = "Input must contain only numbers and commas. Invalid part: '{0}'"
            regWarnMultiUpdate         = "Warning: Multiple Windows Update settings selected. Only the first one will be applied: '{0}'"
            regNothingSelected         = "No registry tweak selected to apply."
            regApplying                = "Applying: {0}"
            regSuccess                 = " -> Success."
            regFail                    = " -> Configuration FAILED: {0}. Error: {1}"
            regQueuedForPostSetup      = " -> Queued for post-setup."
            regPostSetupScriptCreated  = "Post-setup PowerShell script created successfully."
            regManualRunnerCreated     = "Manual runner ({0}) created for the Desktop."
            regErrorGeneral            = "An error occurred during registry operations: {0}"
            regSaving                  = "Saving registry configuration..."
            regComplete                = "Registry configuration complete."
            regReturnToMenu            = "Press any key to return to the main menu..."
            regTweakDefNotFound        = "CRITICAL ERROR: tweak-definitions.ps1 could not be found or loaded."
            regRunnerBatTitle          = "Apply Custom Settings.bat"
            regRunnerBatBody           = "@echo off`necho.`necho This script will apply the custom settings added to the ISO.`necho Please ensure you have an active internet connection.`necho.`npause`necho Applying settings, please wait...`npowershell.exe -ExecutionPolicy Bypass -File ""{0}""`necho.`necho The process is complete. This window will now close and this launcher will be deleted.`ntimeout /t 5`ndel ""%~f0"""
            # App Removal
            appRemoveGettingList       = "Getting the list of installed apps inside the ISO. This might take a moment..."
            appRemoveGetListError      = "Could not get the app list. DISM Exit Code: {0}"
            appRemoveExcludingCritical = "Excluding critical system apps from the list..."
            appRemoveNotFound          = "No removable apps found."
            appRemoveTitle             = "Which apps do you want to remove?"
            appRemoveApplyAll          = "APPLY ALL"
            appRemoveFromConfig        = "Removing apps from configuration file..."
            appRemoveNothingSelected   = "No app selected for removal."
            appRemoveStarting          = "Starting removal process..."
            appRemoveRemoving          = "Removing: {0}"
            appRemoveSuccess           = "Successfully removed: {0}"
            appRemoveFail              = "Failed to remove: {0}. DISM Exit Code: {1}"
            appRemoveError             = "Error while removing {0}: {1}"
            appRemoveComplete          = "App removal process completed."
            appExclusionDefNotFound    = "CRITICAL ERROR: app-exclusion-list.ps1 could not be found or loaded."
            # Feature Enable
            featureEnableFromConfig    = "Enabling features from configuration file..."
            featureEnableTitle         = "Which features do you want to enable?"
            featureEnableApplyAll      = "Enable all recommended features"
            featureEnableNothingSelect = "No feature selected to enable."
            featureEnableEnabling      = "Enabling {0}..."
            featureEnableSuccess       = "Successfully enabled {0}."
            featureEnableError         = "Error: Could not enable {0}. {1}"
            featureDefNotFound         = "CRITICAL ERROR: feature-definitions.ps1 could not be found or loaded."
            # Completion
            completeCreatingIso        = "Creating new ISO..."
            completeToolNotFound       = "ISO creation tool not found or could not be downloaded. Operation canceled."
            completeToolNotFoundHelp   = "Your changes are ready in the C:\temp_iso folder. You can create the ISO manually."
            completeSaveFileTitle      = "Select where to save the output ISO file"
            completeOutputCanceled     = "Output path not selected. ISO creation canceled."
            completeOutputIsoPath      = "Output ISO file path: {0}"
            completeIsoSuccess         = "ISO created successfully: {0}"
            completeIsoError           = "Error creating ISO: {0}"
            completeFilesSaved         = "Your files are preserved in the C:\temp_iso folder."
            completeUnmountFail        = "Unmount/Commit operation failed. Exit Code: {0}"
            completeSaveError          = "`nA critical error occurred while saving the image: {0}"
            completeFinalizeFail       = "Could not finalize the image."
            completeDefaultIsoName     = "Custom_Windows11.iso"
            # Cleanup
            cleanupCleaning            = "Cleaning up temporary files and folders..."
            cleanupImageMounted        = "There is still a mounted image, discarding changes..."
            cleanupComplete            = "Cleanup complete!"
            # Script Start
            langPrompt                 = "Please select a language / Lutfen bir dil secin"
            scriptNotAdmin             = "This script must be run as an administrator!"
            scriptExistingMount        = "An existing mount operation was found. Proceeding directly to the menu..."
            scriptSelectIso            = "Select the Windows 11 ISO file"
            scriptIsoNotSelected       = "ISO file not selected. Exiting script."
            scriptIsoSelected          = "Selected ISO file: {0}"
            scriptIsoInvalid           = "ISO file not found or is invalid: {0}"
            scriptIsoFound             = "ISO file found: {0}"
            scriptMountFail            = "Could not mount the image. Exiting script."
            scriptPromptUpdate         = "Would you like to add Windows Updates? (Y/N)"
            scriptPromptDriver         = "Would you like to add drivers? (Y/N)"
            # Execution Block
            execAutoModeStarted        = "--- AUTOMATIC OPERATIONS STARTED ---"
            execAutoModeCompleted      = "--- AUTOMATIC OPERATIONS COMPLETED ---"
            execAutoPromptManual       = "Automatic operations are complete. Would you like to perform additional actions (switch to manual mode)? (Y/N)"
            execAutoCreateIso          = "Proceeding to ISO creation..."
            # Main Menu
            mainMenu1                  = "1. Add Windows Updates (.msu)"
            mainMenu2                  = "2. Add Drivers (.inf)"
            mainMenu3                  = "3. Remove Components and Configure Services"
            mainMenu4                  = "4. Configure Registry Settings"
            mainMenu5                  = "5. Remove Windows Apps"
            mainMenu6                  = "6. Enable Windows Features"
            mainMenu7                  = "7. Export Settings (.json)"
            mainMenu8                  = "8. Save Changes and Create ISO"
            mainMenu9                  = "9. Exit Without Saving Changes"
            # Finish
            finishMessage              = "Operation completed. Press any key to exit..."
        }
    }
    'ja' {
        # NOT: Bu çeviriler sadece bir örnektir ve makine tarafından çevrilmiştir.
        # Lütfen canlı kullanım için anadili Japonca olan birine kontrol ettirin.
        $global:langStrings = @{
            # Genel
            pressAnyKey                = "続行するには何かキーを押してください..."
            promptChoice               = "あなたの選択"
            goBack                     = "戻る"
            invalidChoice              = "無効な選択です！"
            # Banner
            bannerTitle                = "Windows 11 ISO カスタマイズツール"
            # Hata Yönetimi (Trap)
            trapErrorUnexpected        = "予期しないエラーが発生しました！安全に終了します..."
            trapErrorMessage           = "エラー:"
            trapErrorFallback          = "予期しないエラーが発生しました！安全に終了します..."
            trapMessageFallback        = "エラー:"
            # Uzun Süren İşlemler
            longOpFailed               = "バックグラウンド処理でエラーが発生しました: {0}"
            longOpSavingImage          = "イメージの変更を保存しています。これには時間がかかる場合があります..."
            # Get-UserChoice
            getUserChoiceMultiSelect   = "複数の選択が可能です（例: 1,3,5）、「all」または「g」（戻る）:"
            getUserChoiceSingleSelect  = "あなたの選択 (1-{0} または 'g')"
            # Get-IsoTool
            isoToolOscdimgFound        = "インストール済みのoscdimg.exeが見つかりました。"
            isoToolMkisofsNotFound     = "oscdimg.exeが見つかりません。代替ツール（mkisofs）をダウンロードしています..."
            isoToolMkisofsExists       = "mkisofsは既にダウンロードされています。"
            isoToolDownloadingMkisofs  = "mkisofs.exeをダウンロードしています..."
            isoToolDownloadingCygwin   = "cygwin1.dllをダウンロードしています..."
            isoToolDownloadSuccess     = "mkisofsは正常にダウンロードされました。"
            isoToolDownloadError       = "エラー: 代替ISOツールをダウンロードできませんでした。{0}"
            isoToolDownloadHelp        = "インターネット接続を確認するか、Windows ADKをインストールしてください。"
            isoToolDownloadFail        = "ダウンロードに失敗しました。"
            # Import/Export
            importTitle                = "保存された設定ファイルをインポートしますか？"
            importDesc                 = "「はい」の場合、設定ファイルに基づいて操作が自動的に実行されます。"
            importPrompt               = "あなたの選択 (Y/N)"
            importFileSelectTitle      = "設定ファイルを選択してください (.json)"
            importReadingFile          = "設定ファイルを読み込んでいます: {0}"
            importSuccess              = "設定が正常に読み込まれました！自動モードを開始します..."
            importReadError            = "設定ファイルの読み込み中にエラーが発生しました: {0}"
            importFileNotSelected      = "ファイルが選択されていません。手動設定を続行します。"
            importManualContinue       = "手動設定を続行します。"
            exportTitle                = "現在の設定が.jsonファイルにエクスポートされます。"
            exportFileSaveTitle        = "設定ファイルを保存"
            exportSuccess              = "設定が正常に保存されました: {0}"
            exportError                = "ファイルの保存中にエラーが発生しました: {0}"
            exportCanceled             = "エクスポート操作はキャンセルされました。"
            exportFileName             = "私の設定ファイル.json"
            exportConfigDesc           = "Windows 11 カスタマイズ設定"
            # Ortam Hazırlama
            initEnvPreparing           = "作業環境を準備しています..."
            initEnvSuccess             = "環境の準備ができました！"
            initEnvError               = "環境の準備中にエラーが発生しました: {0}"
            initEnvFail                = "環境を準備できませんでした。"
            # ISO Kopyalama
            copyIsoCopying             = "ISOファイルをコピーしています..."
            copyIsoUnlockingWim        = "install.wimから読み取り専用属性を削除しています..."
            copyIsoSuccess             = "ISOファイルがコピーされました！"
            copyIsoError               = "ISOファイルのコピー中にエラーが発生しました: {0}"
            copyIsoFail                = "ISOのコピーに失敗しました。"
            # DISM Bulma
            dismFound                  = "DISMが見つかりました: {0}"
            dismFoundInPath            = "PATHでDISMが見つかりました: {0}"
            dismNotFoundWarning        = "警告: DISMが見つかりません！Windows ADKまたはシステムのDISMが必要です。"
            dismNotFoundExit           = "DISMが見つからないため、スクリプトを終了します。"
            # Sürüm Kaldırma
            removeEditionsAnalyzing    = "現在のWindowsエディションを分析しています..."
            removeEditionsCurrent      = "現在のエディション:"
            removeEditionsOnlyOne      = "エディションが1つしか残っていません。削除をスキップします。"
            removeEditionsPrompt       = "削除するエディションのインデックス番号を入力してください（カンマ区切り、例: 1,3）"
            removeEditionsGoBack       = "[g] 戻って編集するエディションを選択"
            removeEditionsInvalidIndex = "無効なインデックス番号が見つかりました: {0}。1から{1}の間の値を入力してください。"
            removeEditionsRemoving     = "インデックス {0} を削除しています..."
            removeEditionsSuccess      = "インデックス {0} は正常に削除されました！"
            removeEditionsError        = "インデックス {0} の削除中にエラーが発生しました: {1}"
            removeEditionsListUpdated  = "選択されたエディションが削除されました。リストを更新しています..."
            removeEditionsInvalidInput = "無効な入力です！数値をカンマで区切って入力してください（例: 1,3）。"
            # Image Mount Etme
            mountListingEditions       = "現在のWindowsエディションを一覧表示しています..."
            mountMountingImage         = "WindowsイメージをC:\mountにマウントしています..."
            mountSuccess               = "イメージは正常にマウントされました！"
            mountError                 = "イメージのマウント中にエラーが発生しました: {0}"
            mountFail                  = "マウント操作に失敗しました。"
            mountPromptIndex           = "編集したいWindowsエディションのインデックス番号を入力してください"
            mountInvalidIndex          = "無効なインデックス番号です。"
            # Güncelleme Ekleme
            updatesPromptPath          = "アップデートが含まれるフォルダへのパスを入力してください"
            updatesAdding              = "アップデートを追加しています..."
            updatesAddingFile          = "追加中: {0}"
            updatesAddedFile           = "追加済み: {0}"
            updatesErrorFile           = "{0} の追加中にエラーが発生しました: {1}"
            updatesMsuNotFound         = "指定されたパスに.msu拡張子の更新ファイルが見つかりませんでした。"
            updatesInvalidPath         = "無効なフォルダパスです！"
            # Sürücü Ekleme
            driversPromptPath          = "ドライバーが含まれるメインフォルダへのパスを入力してください"
            driversAdding              = "ドライバーを追加しています..."
            driversSuccess             = "ドライバーは正常に追加されました。"
            driversError               = "ドライバーの追加中にエラーが発生しました: {0}"
            # Bileşen ve Servisler
            compSvcTitle               = "コンポーネントの削除とサービスの構成"
            compSvcApplyingFromConfig  = "設定ファイルからコンポーネントとサービスの設定を適用しています..."
            compSvcApplyAll            = "すべて適用"
            compSvcNothingSelected     = "適用する設定が選択されていません。"
            compSvcConfiguringServices = "サービスを構成しています..."
            compSvcServiceDisabled     = " -> サービス '{0}' は無効化されました。"
            compSvcServiceNotFound     = " -> サービス '{0}' が見つからなかったため、スキップされました。"
            compSvcServiceError        = " -> サービス '{0}' の構成中にエラー: {1}"
            compSvcRemovingComponents  = "コンポーネントを削除しています..."
            compSvcProcessing          = "処理中: {0}"
            compSvcStateEnabled        = " -> 状態: 有効。削除しています..."
            compSvcRemoveSuccess       = " -> 正常に削除されました。"
            compSvcRemoveError         = " -> 削除中にエラーが発生しました。DISM終了コード: {0}"
            compSvcStateNotEnabled     = " -> コンポーネントが有効ではありません（状態: {0}）。操作はスキップされました。"
            compSvcStateError          = " -> コンポーネントの状態を読み取れないか、コンポーнентが見つかりません。操作はスキップされました。"
            compSvcCriticalError       = " -> コンポーネントの状態の確認または削除中に重大なエラーが発生しました: {0}"
            compSvcTweakDefNotFound    = "致命的なエラー: component-definitions.ps1が見つからないか、読み込めませんでした。"
            # Registry Ayarları
            regMenuTitle               = "レジストリ構成メニュー"
            regApplyingFromConfig      = "設定ファイルからレジストリ設定を適用しています..."
            regCurrentSelections       = "現在の選択:"
            regSelectAll               = "すべての調整を選択/選択解除"
            regGoBackAndApply          = "[g] 戻る（メインメニューに戻り、選択を適用）"
            regPrompt                  = "あなたの選択（複数の選択はカンマで区切ってください、例: 1,5,12）"
            regAllSelectionsRemoved    = "すべての選択が解除されました。"
            regAllSelectionsAdded      = "すべての調整が選択されました。"
            regItemRemoved             = "'{0}' が選択から削除されました。"
            regItemAdded               = "'{0}' が選択に追加されました。"
            regInvalidNumber           = "無効な番号: {0}"
            regInvalidInput            = "入力には数字とカンマのみを含めることができます。無効な部分: '{0}'"
            regWarnMultiUpdate         = "警告: 複数のWindows Update設定が選択されています。最初の設定のみが適用されます: '{0}'"
            regNothingSelected         = "適用するレジストリ調整が選択されていません。"
            regApplying                = "適用中: {0}"
            regSuccess                 = " -> 成功。"
            regFail                    = " -> 構成に失敗しました: {0}。エラー: {1}"
            regQueuedForPostSetup      = " -> セットアップ後のためにキューに入れられました。"
            regPostSetupScriptCreated  = "セットアップ後のPowerShellスクリプトが正常に作成されました。"
            regManualRunnerCreated     = "手動実行用のランナー（{0}）がデスクトップに作成されました。"
            regErrorGeneral            = "レジストリ操作中にエラーが発生しました: {0}"
            regSaving                  = "レジストリ構成を保存しています..."
            regComplete                = "レジストリ構成が完了しました。"
            regReturnToMenu            = "何かキーを押してメインメニューに戻ってください..."
            regTweakDefNotFound        = "致命的なエラー: tweak-definitions.ps1が見つからないか、読み込めませんでした。"
            regRunnerBatTitle          = "カスタム設定を適用.bat"
            regRunnerBatBody           = "@echo off`necho.`necho このスクリプトはISOに追加されたカスタム設定を適用します。`necho インターネット接続が有効であることを確認してください。`necho.`npause`necho 設定を適用しています、お待ちください...`npowershell.exe -ExecutionPolicy Bypass -File ""{0}""`necho.`necho 処理が完了しました。このウィンドウは閉じられ、このランチャーは削除されます。`ntimeout /t 5`ndel ""%~f0"""
            # Uygulama Kaldırma
            appRemoveGettingList       = "ISO内のインストール済みアプリのリストを取得しています。これには少し時間がかかる場合があります..."
            appRemoveGetListError      = "アプリのリストを取得できませんでした。DISM終了コード: {0}"
            appRemoveExcludingCritical = "重要なシステムアプリをリストから除外しています..."
            appRemoveNotFound          = "削除可能なアプリが見つかりませんでした。"
            appRemoveTitle             = "どのアプリを削除しますか？"
            appRemoveApplyAll          = "すべて適用"
            appRemoveFromConfig        = "設定ファイルからアプリを削除しています..."
            appRemoveNothingSelected   = "削除するアプリが選択されていません。"
            appRemoveStarting          = "削除処理を開始しています..."
            appRemoveRemoving          = "削除中: {0}"
            appRemoveSuccess           = "正常に削除されました: {0}"
            appRemoveFail              = "削除に失敗しました: {0}。DISM終了コード: {1}"
            appRemoveError             = "{0} の削除中にエラー: {1}"
            appRemoveComplete          = "アプリの削除処理が完了しました。"
            appExclusionDefNotFound    = "致命的なエラー: app-exclusion-list.ps1が見つからないか、読み込めませんでした。"
            # Özellik Ekleme
            featureEnableFromConfig    = "設定ファイルから機能を有効にしています..."
            featureEnableTitle         = "どの機能を有効にしますか？"
            featureEnableApplyAll      = "推奨されるすべての機能を有効にする"
            featureEnableNothingSelect = "有効にする機能が選択されていません。"
            featureEnableEnabling      = "{0} を有効にしています..."
            featureEnableSuccess       = "{0} は正常に有効化されました。"
            featureEnableError         = "エラー: {0} を有効にできませんでした。{1}"
            featureDefNotFound         = "致命的なエラー: feature-definitions.ps1が見つからないか、読み込めませんでした。"
            # Tamamlama
            completeCreatingIso        = "新しいISOを作成しています..."
            completeToolNotFound       = "ISO作成ツールが見つからないか、ダウンロードできませんでした。操作はキャンセルされました。"
            completeToolNotFoundHelp   = "変更はC:\temp_isoフォルダに準備されています。手動でISOを作成できます。"
            completeSaveFileTitle      = "出力ISOファイルの保存場所を選択してください"
            completeOutputCanceled     = "出力パスが選択されていません。ISOの作成はキャンセルされました。"
            completeOutputIsoPath      = "出力ISOファイルパス: {0}"
            completeIsoSuccess         = "ISOは正常に作成されました: {0}"
            completeIsoError           = "ISOの作成中にエラーが発生しました: {0}"
            completeFilesSaved         = "あなたのファイルはC:\temp_isoフォルダに保存されています。"
            completeUnmountFail        = "アンマウント/コミット操作に失敗しました。終了コード: {0}"
            completeSaveError          = "`nイメージの保存中に致命的なエラーが発生しました: {0}"
            completeFinalizeFail       = "イメージをファイナライズできませんでした。"
            completeDefaultIsoName     = "カスタム_Windows11.iso"
            # Temizlik
            cleanupCleaning            = "一時ファイルとフォルダをクリーンアップしています..."
            cleanupImageMounted        = "まだマウントされているイメージがあります。変更を破棄しています..."
            cleanupComplete            = "クリーンアップが完了しました！"
            # Script Başlangıcı
            langPrompt                 = "言語を選択してください / Lutfen bir dil secin"
            scriptNotAdmin             = "このスクリプトは管理者として実行する必要があります！"
            scriptExistingMount        = "既存のマウント操作が見つかりました。直接メニューに進みます..."
            scriptSelectIso            = "Windows 11 ISOファイルを選択してください"
            scriptIsoNotSelected       = "ISOファイルが選択されていません。スクリプトを終了します。"
            scriptIsoSelected          = "選択されたISOファイル: {0}"
            scriptIsoInvalid           = "ISOファイルが見つからないか、無効です: {0}"
            scriptIsoFound             = "ISOファイルが見つかりました: {0}"
            scriptMountFail            = "イメージをマウントできませんでした。スクリプトを終了します。"
            scriptPromptUpdate         = "Windows Updateを追加しますか？ (Y/N)"
            scriptPromptDriver         = "ドライバーを追加しますか？ (Y/N)"
            # Yürütme Bloğu
            execAutoModeStarted        = "--- 自動操作開始 ---"
            execAutoModeCompleted      = "--- 自動操作完了 ---"
            execAutoPromptManual       = "自動操作が完了しました。追加の操作（手動モードに切り替え）を行いますか？ (Y/N)"
            execAutoCreateIso          = "ISO作成に進みます..."
            # Ana Menü
            mainMenu1                  = "1. Windows Updateを追加 (.msu)"
            mainMenu2                  = "2. ドライバーを追加 (.inf)"
            mainMenu3                  = "3. コンポーネントの削除とサービスの構成"
            mainMenu4                  = "4. レジストリ設定の構成"
            mainMenu5                  = "5. Windowsアプリを削除"
            mainMenu6                  = "6. Windowsの機能を有効にする"
            mainMenu7                  = "7. 設定をエクスポート (.json)"
            mainMenu8                  = "8. 変更を保存してISOを作成"
            mainMenu9                  = "9. 変更を保存せずに終了"
            # Bitiş
            finishMessage              = "操作が完了しました。何かキーを押して終了してください..."
        }
    }
    default {
        # Eğer geçersiz bir dil seçilirse varsayılan olarak İngilizce kullanılır.
        Write-Host "Invalid language. Defaulting to English." -ForegroundColor Yellow
        $global:currentLanguage = 'en'
        # Bu script'i yeniden çalıştırarak İngilizce metinleri yükle
        . $PSCommandPath
    }
}

