# Language Strings
# Supported languages: English (en), Turkish (tr)
# To add a new language, create a new hashtable with the appropriate translations.

switch ($global:currentLanguage) {
    'tr' {
        $global:langStrings = @{
            # Genel
            pressAnyKey                = "Devam etmek için herhangi bir tuşa basın..."
            promptChoice               = "Seçiminiz"
            goBack                     = "Geri"
            invalidChoice              = "Geçersiz seçim!"
            # Banner
            bannerTitle                = "Windows 11 ISO Özelleştirme Aracı"
            # Hata Yönetimi (Trap)
            trapErrorUnexpected        = "Beklenmedik bir hata oluştu! Güvenli çıkış yapılıyor..."
            trapErrorMessage           = "Hata:"
            trapErrorFallback          = "Beklenmedik bir hata oluştu! Güvenli çıkış yapılıyor..." # Dil dosyası yüklenemezse kullanılır
            trapMessageFallback        = "Hata:" # Dil dosyası yüklenemezse kullanılır
            # Uzun Süren İşlemler
            longOpFailed               = "Arka plan işleminde hata oluştu: {0}"
            longOpSavingImage          = "Image değişiklikleri kaydediliyor, bu işlem uzun sürebilir..."
            # Get-UserChoice
            getUserChoiceMultiSelect   = "Birden fazla seçim yapabilirsiniz (örn: 1,3,5), 'tümü' veya 'g' (geri):"
            getUserChoiceSingleSelect  = "Seçiminiz (1-{0} veya 'g')"
            # Get-IsoTool
            isoToolOscdimgFound        = "Sistemde kurulu oscdimg.exe bulundu."
            isoToolMkisofsNotFound     = "Sistemde oscdimg.exe bulunamadı. Alternatif araç (mkisofs) indiriliyor..."
            isoToolMkisofsExists       = "mkisofs zaten indirilmiş."
            isoToolDownloadingMkisofs  = "mkisofs.exe indiriliyor..."
            isoToolDownloadingCygwin   = "cygwin1.dll indiriliyor..."
            isoToolDownloadSuccess     = "mkisofs başarıyla indirildi."
            isoToolDownloadError       = "Hata: Alternatif ISO aracı indirilemedi. {0}"
            isoToolDownloadHelp        = "Lütfen internet bağlantınızı kontrol edin veya Windows ADK'yı yükleyin."
            isoToolDownloadFail        = "İndirme başarısız oldu."
            # Import/Export
            importTitle                = "Kaydedilmiş bir yapılandırma dosyasını içe aktarmak ister misiniz?"
            importDesc                 = "Evet derseniz, işlemler yapılandırma dosyanıza göre otomatik olarak yapılacaktır."
            importPrompt               = "Seçiminiz (E/H)"
            importFileSelectTitle      = "Yapılandırma dosyasını seçin (.json)"
            importReadingFile          = "Yapılandırma dosyası okunuyor: {0}"
            importSuccess              = "Yapılandırma başarıyla yüklendi! Otomatik mod başlatılıyor..."
            importReadError            = "Yapılandırma dosyası okunurken hata oluştu: {0}"
            importFileNotSelected      = "Dosya seçilmedi. Manuel yapılandırmaya devam ediliyor."
            importManualContinue       = "Manuel yapılandırmaya devam ediliyor."
            exportTitle                = "Mevcut ayarlar bir .json dosyasına aktarılacak."
            exportFileSaveTitle        = "Yapılandırma dosyasını kaydet"
            exportSuccess              = "Yapılandırma başarıyla kaydedildi: {0}"
            exportError                = "Dosya kaydedilirken hata oluştu: {0}"
            exportCanceled             = "Dışa aktarma işlemi iptal edildi."
            exportFileName             = "Yapılandırma Dosyam.json"
            exportConfigDesc           = "Windows 11 Özelleştirme Ayarları"
            # Ortam Hazırlama
            initEnvPreparing           = "Çalışma ortamı hazırlanıyor..."
            initEnvSuccess             = "Ortam hazırlandı!"
            initEnvError               = "Ortam hazırlanırken hata oluştu: {0}"
            initEnvFail                = "Ortam hazırlanamadı."
            # ISO Kopyalama
            copyIsoCopying             = "ISO dosyaları kopyalanıyor..."
            copyIsoUnlockingWim        = "install.wim dosyasının salt okunur özelliği kaldırılıyor..."
            copyIsoSuccess             = "ISO dosyaları kopyalandı!"
            copyIsoError               = "ISO dosyaları kopyalanırken hata oluştu: {0}"
            copyIsoFail                = "ISO kopyalama başarısız."
            # DISM Bulma
            dismFound                  = "DISM bulundu: {0}"
            dismFoundInPath            = "DISM PATH'te bulundu: {0}"
            dismNotFoundWarning        = "UYARI: DISM bulunamadı! Windows ADK veya system DISM gerekli."
            dismNotFoundExit           = "DISM bulunamadığı için script sonlandırılıyor."
            # Sürüm Kaldırma
            removeEditionsAnalyzing    = "Mevcut Windows sürümleri analiz ediliyor..."
            removeEditionsCurrent      = "Mevcut sürümler:"
            removeEditionsOnlyOne      = "Yalnızca bir sürüm kaldı. Silme işlemi atlandı."
            removeEditionsPrompt       = "Kaldırmak istediğiniz sürümlerin index numaralarını girin (virgülle ayırarak, örn: 1,3)"
            removeEditionsGoBack       = "[g] Geri dön ve düzenlenecek sürümü seç"
            removeEditionsInvalidIndex = "Geçersiz index numarası bulundu: {0}. Lütfen 1 ile {1} arasında değerler girin."
            removeEditionsRemoving     = "Index {0} kaldırılıyor..."
            removeEditionsSuccess      = "Index {0} başarıyla kaldırıldı!"
            removeEditionsError        = "Index {0} kaldırılırken hata oluştu: {1}"
            removeEditionsListUpdated  = "Seçilen sürümler kaldırıldı. Liste güncelleniyor..."
            removeEditionsInvalidInput = "Geçersiz giriş! Lütfen sayıları virgülle ayırarak girin (örn: 1,3)."
            # Image Mount Etme
            mountListingEditions       = "Mevcut Windows sürümleri listeleniyor..."
            mountMountingImage         = "Windows imajı C:\mount dizinine mount ediliyor..."
            mountSuccess               = "İmaj başarıyla mount edildi!"
            mountError                 = "İmaj mount edilirken hata oluştu: {0}"
            mountFail                  = "Mount işlemi başarısız."
            mountPromptIndex           = "Düzenleme yapmak istediğiniz Windows sürümünün index numarasını girin"
            mountInvalidIndex          = "Geçersiz index numarası."
            # Güncelleme Ekleme
            updatesPromptPath          = "Güncellemelerin bulunduğu klasörün yolunu girin"
            updatesAdding              = "Güncellemeler ekleniyor..."
            updatesAddingFile          = "Ekleniyor: {0}"
            updatesAddedFile           = "Eklendi: {0}"
            updatesErrorFile           = "{0} eklenirken hata oluştu: {1}"
            updatesMsuNotFound         = "Belirtilen yolda .msu uzantılı güncelleme dosyası bulunamadı."
            updatesInvalidPath         = "Geçersiz klasör yolu!"
            # Sürücü Ekleme
            driversPromptPath          = "Sürücülerin bulunduğu ana klasörün yolunu girin"
            driversAdding              = "Sürücüler ekleniyor..."
            driversSuccess             = "Sürücüler başarıyla eklendi."
            driversError               = "Sürücüler eklenirken hata oluştu: {0}"
            # Bileşen ve Servisler
            compSvcTitle               = "Bileşenleri Kaldır ve Servisleri Yapılandır"
            compSvcApplyingFromConfig  = "Yapılandırma dosyasından bileşen ve servis ayarları uygulanıyor..."
            compSvcApplyAll            = "TÜMÜNÜ UYGULA"
            compSvcNothingSelected     = "Uygulanacak ayar seçilmedi."
            compSvcConfiguringServices = "Servisler yapılandırılıyor..."
            compSvcServiceDisabled     = " -> '{0}' servisi devre dışı bırakıldı."
            compSvcServiceNotFound     = " -> '{0}' servisi bulunamadı, atlandı."
            compSvcServiceError        = " -> '{0}' servisi yapılandırılırken hata: {1}"
            compSvcRemovingComponents  = "Bileşenler kaldırılıyor..."
            compSvcProcessing          = "İşlem yapılıyor: {0}"
            compSvcStateEnabled        = " -> Durum: Etkin. Kaldırılıyor..."
            compSvcRemoveSuccess       = " -> Başarıyla kaldırıldı."
            compSvcRemoveError         = " -> Kaldırılırken hata oluştu. DISM Exit Code: {0}"
            compSvcStateNotEnabled     = " -> Bileşen etkin değil (Durum: {0}). İşlem atlandı."
            compSvcStateError          = " -> Bileşen durumu okunamadı veya bileşen bulunamadı. İşlem atlandı."
            compSvcCriticalError       = " -> Bileşen durumu kontrol edilirken veya kaldırılırken kritik hata: {0}"
            compSvcTweakDefNotFound    = "KRİTİK HATA: component-definitions.ps1 bulunamadı veya yüklenemedi."
            # Registry Ayarları
            regMenuTitle               = "Registry Yapılandırma Menüsü"
            regApplyingFromConfig      = "Yapılandırma dosyasından registry ayarları uygulanıyor..."
            regCurrentSelections       = "Şu anki seçimleriniz:"
            regSelectAll               = "TÜM AYARLARI SEÇ/KALDIR"
            regGoBackAndApply          = "[g] Geri (Ana Menüye Dön ve Seçimleri Uygula)"
            regPrompt                  = "Seçiminiz (Birden fazla seçim için virgülle ayırın, örn: 1,5,12)"
            regAllSelectionsRemoved    = "Tüm seçimler kaldırıldı."
            regAllSelectionsAdded      = "Tüm ayarlar seçildi."
            regItemRemoved             = "'{0}' seçimlerden kaldırıldı."
            regItemAdded               = "'{0}' seçimlere eklendi."
            regInvalidNumber           = "Geçersiz numara: {0}"
            regInvalidInput            = "Giriş sadece sayı ve virgül içermelidir. Hatalı bölüm: '{0}'"
            regWarnMultiUpdate         = "Uyarı: Birden fazla Windows Update ayarı seçildi. Yalnızca ilki uygulanacak: '{0}'"
            regNothingSelected         = "Uygulanacak registry ayarı seçilmedi."
            regApplying                = "Uygulanıyor: {0}"
            regSuccess                 = " -> Başarılı."
            regFail                    = " -> Yapılandırma BAŞARISIZ oldu: {0}. Hata: {1}"
            regQueuedForPostSetup      = " -> Kurulum sonrası için sıraya eklendi."
            regPostSetupScriptCreated  = "Kurulum sonrası PowerShell script'i başarıyla oluşturuldu."
            regManualRunnerCreated     = "Masaüstü için manuel çalıştırıcı ({0}) oluşturuldu."
            regErrorGeneral            = "Registry işlemleri sırasında bir hata oluştu: {0}"
            regSaving                  = "Registry yapılandırması kaydediliyor..."
            regComplete                = "Registry yapılandırması tamamlandı."
            regReturnToMenu            = "Ana menüye dönmek için herhangi bir tuşa basın..."
            regTweakDefNotFound        = "KRİTİK HATA: tweak-definitions.ps1 bulunamadı veya yüklenemedi."
            regRunnerBatTitle          = "Özel Ayarları Uygula.bat"
            regRunnerBatBody           = "@echo off`necho.`necho Bu script, ISO'ya eklenen özel ayarları uygulayacaktır.`necho Lütfen internet bağlantınızın aktif olduğundan emin olun.`necho.`npause`necho Ayarlar uygulanıyor, lütfen bekleyin...`npowershell.exe -ExecutionPolicy Bypass -File ""{0}""`necho.`necho İşlem tamamlandı. Bu pencere şimdi kapatılacak ve bu başlatıcı silinecek.`ntimeout /t 5`ndel ""%~f0"""
            # Uygulama Kaldırma
            appRemoveGettingList       = "ISO içindeki kurulu uygulamaların listesi alınıyor. Bu işlem biraz sürebilir..."
            appRemoveGetListError      = "Uygulama listesi alınamadı. DISM Exit Code: {0}"
            appRemoveExcludingCritical = "Kritik sistem uygulamaları liste dışı bırakılıyor..."
            appRemoveNotFound          = "Kaldırılabilecek uygulama bulunamadı."
            appRemoveTitle             = "Hangi uygulamaları kaldırmak istiyorsunuz?"
            appRemoveApplyAll          = "TÜMÜNÜ UYGULA"
            appRemoveFromConfig        = "Yapılandırma dosyasından uygulamalar kaldırılıyor..."
            appRemoveNothingSelected   = "Kaldırılacak uygulama seçilmedi."
            appRemoveStarting          = "Kaldırma işlemi başlıyor..."
            appRemoveRemoving          = "Kaldırılıyor: {0}"
            appRemoveSuccess           = "Başarıyla kaldırıldı: {0}"
            appRemoveFail              = "Kaldırılamadı: {0}. DISM Exit Code: {1}"
            appRemoveError             = "{0} kaldırılırken hata: {1}"
            appRemoveComplete          = "Uygulama kaldırma işlemi tamamlandı."
            appExclusionDefNotFound    = "KRİTİK HATA: app-exclusion-list.ps1 bulunamadı veya yüklenemedi."
            # Özellik Ekleme
            featureEnableFromConfig    = "Yapılandırma dosyasından özellikler etkinleştiriliyor..."
            featureEnableTitle         = "Hangi özellikleri etkinleştirmek istiyorsunuz?"
            featureEnableApplyAll      = "Tüm önerilen özellikleri etkinleştir"
            featureEnableNothingSelect = "Etkinleştirilecek özellik seçilmedi."
            featureEnableEnabling      = "{0} etkinleştiriliyor..."
            featureEnableSuccess       = "{0} başarıyla etkinleştirildi."
            featureEnableError         = "Hata: {0} etkinleştirilemedi. {1}"
            featureDefNotFound         = "KRİTİK HATA: feature-definitions.ps1 bulunamadı veya yüklenemedi."
            # Tamamlama
            completeCreatingIso        = "Yeni ISO oluşturuluyor..."
            completeToolNotFound       = "ISO oluşturma aracı bulunamadı veya indirilemedi. İşlem iptal ediliyor."
            completeToolNotFoundHelp   = "Değişiklikleriniz C:\temp_iso klasöründe hazır durumda. ISO'yu manuel oluşturabilirsiniz."
            completeSaveFileTitle      = "Çıktı ISO dosyasının kaydedileceği yeri seçin"
            completeOutputCanceled     = "Çıktı yolu seçilmedi. ISO oluşturma iptal edildi."
            completeOutputIsoPath      = "Çıktı ISO dosyası yolu: {0}"
            completeIsoSuccess         = "ISO başarıyla oluşturuldu: {0}"
            completeIsoError           = "ISO oluşturulurken hata oluştu: {0}"
            completeFilesSaved         = "Dosyalarınız C:\temp_iso klasöründe korunuyor."
            completeUnmountFail        = "Unmount/Commit işlemi başarısız oldu. Çıkış Kodu: {0}"
            completeSaveError          = "`nİmaj kaydedilirken kritik bir hata oluştu: {0}"
            completeFinalizeFail       = "İmaj sonlandırılamadı."
            completeDefaultIsoName     = "Özel_Windows11.iso"
            # Temizlik
            cleanupCleaning            = "Geçici dosyalar ve klasörler temizleniyor..."
            cleanupImageMounted        = "Hala mount edilmiş bir imaj var, değişiklikler iptal ediliyor..."
            cleanupComplete            = "Temizlik tamamlandı!"
            # Script Başlangıcı
            langPrompt                 = "Lütfen bir dil seçin / Please select a language"
            scriptNotAdmin             = "Bu script yönetici olarak çalıştırılmalıdır!"
            scriptExistingMount        = "Mevcut bir mount işlemi bulundu. Doğrudan menüye geçiliyor..."
            scriptSelectIso            = "Windows 11 ISO dosyasını seçin"
            scriptIsoNotSelected       = "ISO dosyası seçilmedi. Script sonlandırılıyor."
            scriptIsoSelected          = "Seçilen ISO dosyası: {0}"
            scriptIsoInvalid           = "ISO dosyası bulunamadı veya geçersiz: {0}"
            scriptIsoFound             = "ISO dosyası bulundu: {0}"
            scriptMountFail            = "İmaj mount edilemedi. Script sonlandırılıyor."
            scriptPromptUpdate         = "Windows Güncellemesi eklemek ister misiniz? (E/H)"
            scriptPromptDriver         = "Sürücü eklemek ister misiniz? (E/H)"
            # Yürütme Bloğu
            execAutoModeStarted        = "--- OTOMATIK ISLEMLER BASLATILDI ---"
            execAutoModeCompleted      = "--- OTOMATIK ISLEMLER TAMAMLANDI ---"
            execAutoPromptManual       = "Otomatik işlemler tamamlandı. Ekstra bir işlem yapmak (manuel moda geçmek) ister misiniz? (E/H)"
            execAutoCreateIso          = "ISO oluşturma aşamasına geçiliyor..."
            # Ana Menü
            mainMenu1                  = "1. Windows Güncellemesi Ekle (.msu)"
            mainMenu2                  = "2. Sürücü Ekle (.inf)"
            mainMenu3                  = "3. Bileşenleri Kaldır ve Servisleri Yapılandır"
            mainMenu4                  = "4. Registry Ayarlarını Yapılandır"
            mainMenu5                  = "5. Windows Uygulamalarını Kaldır"
            mainMenu6                  = "6. Windows Özelliklerini Etkinleştir"
            mainMenu7                  = "7. Ayarları Dışa Aktar (.json)"
            mainMenu8                  = "8. Değişiklikleri Kaydet ve ISO Oluştur"
            mainMenu9                  = "9. Değişiklikleri Kaydetme ve Çık"
            # Bitiş
            finishMessage              = "İşlem tamamlandı. Çıkmak için herhangi bir tuşa basın..."
        }
    }
    'en' {
        $global:langStrings = @{
            # General
            pressAnyKey                = "Press any key to continue..."
            promptChoice               = "Your choice"
            goBack                     = "Back"
            invalidChoice              = "Invalid choice!"
            # Banner
            bannerTitle                = "Windows 11 ISO Customization Tool"
            # Trap
            trapErrorUnexpected        = "An unexpected error occurred! Exiting safely..."
            trapErrorMessage           = "Error:"
            trapErrorFallback          = "An unexpected error occurred! Exiting safely..." # Fallback if lang file fails
            trapMessageFallback        = "Error:" # Fallback if lang file fails
            # Long Running Operation
            longOpFailed               = "An error occurred in the background job: {0}"
            longOpSavingImage          = "Saving image changes, this may take a long time..."
            # Get-UserChoice
            getUserChoiceMultiSelect   = "You can make multiple selections (e.g., 1,3,5), 'all' or 'g' (back):"
            getUserChoiceSingleSelect  = "Your choice (1-{0} or 'g')"
            # Get-IsoTool
            isoToolOscdimgFound        = "Found installed oscdimg.exe."
            isoToolMkisofsNotFound     = "oscdimg.exe not found. Downloading alternative tool (mkisofs)..."
            isoToolMkisofsExists       = "mkisofs is already downloaded."
            isoToolDownloadingMkisofs  = "Downloading mkisofs.exe..."
            isoToolDownloadingCygwin   = "Downloading cygwin1.dll..."
            isoToolDownloadSuccess     = "mkisofs downloaded successfully."
            isoToolDownloadError       = "Error: Could not download the alternative ISO tool. {0}"
            isoToolDownloadHelp        = "Please check your internet connection or install the Windows ADK."
            isoToolDownloadFail        = "Download failed."
            # Import/Export
            importTitle                = "Would you like to import a saved configuration file?"
            importDesc                 = "If yes, operations will be performed automatically based on your configuration file."
            importPrompt               = "Your choice (Y/N)"
            importFileSelectTitle      = "Select the configuration file (.json)"
            importReadingFile          = "Reading configuration file: {0}"
            importSuccess              = "Configuration loaded successfully! Starting automatic mode..."
            importReadError            = "Error reading configuration file: {0}"
            importFileNotSelected      = "No file selected. Continuing with manual configuration."
            importManualContinue       = "Continuing with manual configuration."
            exportTitle                = "Current settings will be exported to a .json file."
            exportFileSaveTitle        = "Save configuration file"
            exportSuccess              = "Configuration successfully saved: {0}"
            exportError                = "Error saving file: {0}"
            exportCanceled             = "Export operation canceled."
            exportFileName             = "My Configuration File.json"
            exportConfigDesc           = "Windows 11 Customization Settings"
            # Environment Init
            initEnvPreparing           = "Preparing working environment..."
            initEnvSuccess             = "Environment prepared!"
            initEnvError               = "Error preparing environment: {0}"
            initEnvFail                = "Could not prepare environment."
            # ISO Copy
            copyIsoCopying             = "Copying ISO files..."
            copyIsoUnlockingWim        = "Removing read-only attribute from install.wim..."
            copyIsoSuccess             = "ISO files copied!"
            copyIsoError               = "Error copying ISO files: {0}"
            copyIsoFail                = "ISO copy failed."
            # DISM Find
            dismFound                  = "DISM found: {0}"
            dismFoundInPath            = "DISM found in PATH: {0}"
            dismNotFoundWarning        = "WARNING: DISM not found! Windows ADK or system DISM is required."
            dismNotFoundExit           = "Exiting script because DISM could not be found."
            # Remove Editions
            removeEditionsAnalyzing    = "Analyzing current Windows editions..."
            removeEditionsCurrent      = "Current editions:"
            removeEditionsOnlyOne      = "Only one edition left. Skipping deletion."
            removeEditionsPrompt       = "Enter the index numbers of the editions to remove (comma-separated, e.g., 1,3)"
            removeEditionsGoBack       = "[g] Go back and select edition to edit"
            removeEditionsInvalidIndex = "Invalid index number found: {0}. Please enter values between 1 and {1}."
            removeEditionsRemoving     = "Removing index {0}..."
            removeEditionsSuccess      = "Index {0} successfully removed!"
            removeEditionsError        = "Error removing index {0}: {1}"
            removeEditionsListUpdated  = "Selected editions removed. Updating list..."
            removeEditionsInvalidInput = "Invalid input! Please enter numbers separated by commas (e.g., 1,3)."
            # Mount Image
            mountListingEditions       = "Listing current Windows editions..."
            mountMountingImage         = "Mounting Windows image to C:\mount..."
            mountSuccess               = "Image mounted successfully!"
            mountError                 = "Error mounting image: {0}"
            mountFail                  = "Mount operation failed."
            mountPromptIndex           = "Enter the index number of the Windows edition you want to edit"
            mountInvalidIndex          = "Invalid index number."
            # Add Updates
            updatesPromptPath          = "Enter the path to the folder containing the updates"
            updatesAdding              = "Adding updates..."
            updatesAddingFile          = "Adding: {0}"
            updatesAddedFile           = "Added: {0}"
            updatesErrorFile           = "Error adding {0}: {1}"
            updatesMsuNotFound         = "No update file with .msu extension found in the specified path."
            updatesInvalidPath         = "Invalid folder path!"
            # Add Drivers
            driversPromptPath          = "Enter the path to the main folder containing the drivers"
            driversAdding              = "Adding drivers..."
            driversSuccess             = "Drivers added successfully."
            driversError               = "Error adding drivers: {0}"
            # Components and Services
            compSvcTitle               = "Remove Components and Configure Services"
            compSvcApplyingFromConfig  = "Applying component and service settings from configuration file..."
            compSvcApplyAll            = "APPLY ALL"
            compSvcNothingSelected     = "No setting selected to apply."
            compSvcConfiguringServices = "Configuring services..."
            compSvcServiceDisabled     = " -> Service '{0}' disabled."
            compSvcServiceNotFound     = " -> Service '{0}' not found, skipped."
            compSvcServiceError        = " -> Error configuring service '{0}': {1}"
            compSvcRemovingComponents  = "Removing components..."
            compSvcProcessing          = "Processing: {0}"
            compSvcStateEnabled        = " -> State: Enabled. Removing..."
            compSvcRemoveSuccess       = " -> Successfully removed."
            compSvcRemoveError         = " -> Error during removal. DISM Exit Code: {0}"
            compSvcStateNotEnabled     = " -> Component not enabled (State: {0}). Operation skipped."
            compSvcStateError          = " -> Could not read component state or component not found. Operation skipped."
            compSvcCriticalError       = " -> Critical error while checking or removing component state: {0}"
            compSvcTweakDefNotFound    = "CRITICAL ERROR: component-definitions.ps1 could not be found or loaded."
            # Registry Tweaks
            regMenuTitle               = "Registry Configuration Menu"
            regApplyingFromConfig      = "Applying registry settings from configuration file..."
            regCurrentSelections       = "Your current selections:"
            regSelectAll               = "SELECT/DESELECT ALL TWEAKS"
            regGoBackAndApply          = "[g] Back (Return to Main Menu and Apply Selections)"
            regPrompt                  = "Your choice (separate multiple choices with a comma, e.g., 1,5,12)"
            regAllSelectionsRemoved    = "All selections have been removed."
            regAllSelectionsAdded      = "All tweaks have been selected."
            regItemRemoved             = "'{0}' removed from selections."
            regItemAdded               = "'{0}' added to selections."
            regInvalidNumber           = "Invalid number: {0}"
            regInvalidInput            = "Input must contain only numbers and commas. Invalid part: '{0}'"
            regWarnMultiUpdate         = "Warning: Multiple Windows Update settings selected. Only the first one will be applied: '{0}'"
            regNothingSelected         = "No registry tweak selected to apply."
            regApplying                = "Applying: {0}"
            regSuccess                 = " -> Success."
            regFail                    = " -> Configuration FAILED: {0}. Error: {1}"
            regQueuedForPostSetup      = " -> Queued for post-setup."
            regPostSetupScriptCreated  = "Post-setup PowerShell script created successfully."
            regManualRunnerCreated     = "Manual runner ({0}) created for the Desktop."
            regErrorGeneral            = "An error occurred during registry operations: {0}"
            regSaving                  = "Saving registry configuration..."
            regComplete                = "Registry configuration complete."
            regReturnToMenu            = "Press any key to return to the main menu..."
            regTweakDefNotFound        = "CRITICAL ERROR: tweak-definitions.ps1 could not be found or loaded."
            regRunnerBatTitle          = "Apply Custom Settings.bat"
            regRunnerBatBody           = "@echo off`necho.`necho This script will apply the custom settings added to the ISO.`necho Please ensure you have an active internet connection.`necho.`npause`necho Applying settings, please wait...`npowershell.exe -ExecutionPolicy Bypass -File ""{0}""`necho.`necho The process is complete. This window will now close and this launcher will be deleted.`ntimeout /t 5`ndel ""%~f0"""
            # App Removal
            appRemoveGettingList       = "Getting the list of installed apps inside the ISO. This might take a moment..."
            appRemoveGetListError      = "Could not get the app list. DISM Exit Code: {0}"
            appRemoveExcludingCritical = "Excluding critical system apps from the list..."
            appRemoveNotFound          = "No removable apps found."
            appRemoveTitle             = "Which apps do you want to remove?"
            appRemoveApplyAll          = "APPLY ALL"
            appRemoveFromConfig        = "Removing apps from configuration file..."
            appRemoveNothingSelected   = "No app selected for removal."
            appRemoveStarting          = "Starting removal process..."
            appRemoveRemoving          = "Removing: {0}"
            appRemoveSuccess           = "Successfully removed: {0}"
            appRemoveFail              = "Failed to remove: {0}. DISM Exit Code: {1}"
            appRemoveError             = "Error while removing {0}: {1}"
            appRemoveComplete          = "App removal process completed."
            appExclusionDefNotFound    = "CRITICAL ERROR: app-exclusion-list.ps1 could not be found or loaded."
            # Feature Enable
            featureEnableFromConfig    = "Enabling features from configuration file..."
            featureEnableTitle         = "Which features do you want to enable?"
            featureEnableApplyAll      = "Enable all recommended features"
            featureEnableNothingSelect = "No feature selected to enable."
            featureEnableEnabling      = "Enabling {0}..."
            featureEnableSuccess       = "Successfully enabled {0}."
            featureEnableError         = "Error: Could not enable {0}. {1}"
            featureDefNotFound         = "CRITICAL ERROR: feature-definitions.ps1 could not be found or loaded."
            # Completion
            completeCreatingIso        = "Creating new ISO..."
            completeToolNotFound       = "ISO creation tool not found or could not be downloaded. Operation canceled."
            completeToolNotFoundHelp   = "Your changes are ready in the C:\temp_iso folder. You can create the ISO manually."
            completeSaveFileTitle      = "Select where to save the output ISO file"
            completeOutputCanceled     = "Output path not selected. ISO creation canceled."
            completeOutputIsoPath      = "Output ISO file path: {0}"
            completeIsoSuccess         = "ISO created successfully: {0}"
            completeIsoError           = "Error creating ISO: {0}"
            completeFilesSaved         = "Your files are preserved in the C:\temp_iso folder."
            completeUnmountFail        = "Unmount/Commit operation failed. Exit Code: {0}"
            completeSaveError          = "`nA critical error occurred while saving the image: {0}"
            completeFinalizeFail       = "Could not finalize the image."
            completeDefaultIsoName     = "Custom_Windows11.iso"
            # Cleanup
            cleanupCleaning            = "Cleaning up temporary files and folders..."
            cleanupImageMounted        = "There is still a mounted image, discarding changes..."
            cleanupComplete            = "Cleanup complete!"
            # Script Start
            langPrompt                 = "Please select a language / Lutfen bir dil secin"
            scriptNotAdmin             = "This script must be run as an administrator!"
            scriptExistingMount        = "An existing mount operation was found. Proceeding directly to the menu..."
            scriptSelectIso            = "Select the Windows 11 ISO file"
            scriptIsoNotSelected       = "ISO file not selected. Exiting script."
            scriptIsoSelected          = "Selected ISO file: {0}"
            scriptIsoInvalid           = "ISO file not found or is invalid: {0}"
            scriptIsoFound             = "ISO file found: {0}"
            scriptMountFail            = "Could not mount the image. Exiting script."
            scriptPromptUpdate         = "Would you like to add Windows Updates? (Y/N)"
            scriptPromptDriver         = "Would you like to add drivers? (Y/N)"
            # Execution Block
            execAutoModeStarted        = "--- AUTOMATIC OPERATIONS STARTED ---"
            execAutoModeCompleted      = "--- AUTOMATIC OPERATIONS COMPLETED ---"
            execAutoPromptManual       = "Automatic operations are complete. Would you like to perform additional actions (switch to manual mode)? (Y/N)"
            execAutoCreateIso          = "Proceeding to ISO creation..."
            # Main Menu
            mainMenu1                  = "1. Add Windows Updates (.msu)"
            mainMenu2                  = "2. Add Drivers (.inf)"
            mainMenu3                  = "3. Remove Components and Configure Services"
            mainMenu4                  = "4. Configure Registry Settings"
            mainMenu5                  = "5. Remove Windows Apps"
            mainMenu6                  = "6. Enable Windows Features"
            mainMenu7                  = "7. Export Settings (.json)"
            mainMenu8                  = "8. Save Changes and Create ISO"
            mainMenu9                  = "9. Exit Without Saving Changes"
            # Finish
            finishMessage              = "Operation completed. Press any key to exit..."
        }
    }
    default {
        # If the language is not recognized, default to English
        Write-Host "Invalid language. Defaulting to English." -ForegroundColor Yellow
        $global:currentLanguage = 'en'
        # Reload English text by re-running this script
        . $PSCommandPath
    }
}

